### ISSUE TITLE
Launching python script in test environment

### ISSUE THREAD

**Issue by brbsix** [pytest-dev/pytest-runner#13]
Some of my tests are like the one below:

```
def test_integration_is_a_tty():
    """Simulate TTY to ensure output is as expected (terminal codes and all)."""

    stdout_wanted = '\x1b[1mcontent\x1b[0m\n'

    # unbuffer disables the output buffering that occurs when program
    # output is redirected from non-interactive programs
    # NOTE: install expect or expect-dev
    command = 'unbuffer python3 -m module.module --options'

    # the following is a rough approximation of unbuffer that should be
    # available on most systems (doesn't require installation of expect)
    # command = "script -eqfc 'python3 -m module.module --options' /dev/null"

    status, stdout = subprocess.getstatusoutput(command)

    assert stdout == stdout_wanted and status is 0
```

As you can imagine, it fails due to missing dependencies. Does anyone know if it is possible to launch a new interpreter in the test environment?

**Comment by jaraco** [comment]
Yes!

I've had this same issue, and solved it with a hack - setting PYTHONPATH to match the current sys.path. Here's [one example](https://github.com/yougov/pmxbot/blob/master/tests/functional/__init__.py#L56-L66).

I haven't implemented this approach within pytest-runner (by setting PYTHONPATH automatically) because I'm not confident the approach works in general. For example, if the user is already relying on PYTHONPATH for packages in the path, then it shouldn't be overwritten, but extended (or prepended). 

Let me know if that helps your situation and what your thoughts are on pytest-runner supporting this scenario more generally.
