### ISSUE TITLE
Declare Setuptools dependency

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest-runner#40]
In #39, it comes to my attention that pytest-runner may be able to declare its minimum (run-time) dependency on setuptools. That seems reasonable to me. Let's try it and see what happens.

**Comment by spjwebster** [comment]
FYI this broke one of our applications with an indirect dependency on pytest-runner via a dependency on fprimex/zdesk. This application is running in an environment that's still running on setuptools 2.2,  and was previously functioning just fine. Unfortunately this application runs in an autoscaling environment, so in scaling up new servers were unable to complete their bootstrapping process due to the version conflict on setuptools.

We've mitigated the issue, but I thought you might want the feedback given the "Let's try it and see what happens" above. Other people may be in a similar situation and be suffering outages or issues this morning.

**Comment by jayvdb** [comment]
Also this breaks any py33 users.  See log at https://travis-ci.org/jayvdb/coala-bears/jobs/354958462

**Comment by jaraco** [comment]
Both Setuptools and Pytest-Runner still apparently support Python 3.3, so I don't think the Python version is relevant. I'm pretty sure the issue in jayvdb/coala-bears is similar to the other issue - that pytest runner, by declaring its dependency, is breaking builds that weren't even invoking pytest-runner. I'd forgotten how common that use-case is, a use case which is borne due to way `setup_requires` dependencies are declared.

I'm somewhat inclined to remove this declaration given the impact it's shown already.

I know what we can do. We can make the dependency a runtime dependency - and not an install dependency. That will avoid the VersionConflict except when pytest-runner is invoked.

**Comment by jaraco** [comment]
Sorry for the trouble. 4.2 is releasing now and should eliminate these failures in environments that aren't actually invoking pytest-runner. Please confirm this change addresses your concerns.
