### ISSUE TITLE
Support setup.py test arguments

### ISSUE THREAD

**Issue by jayvdb** [pytest-dev/pytest-runner#46]
There are two arguments for setuptools `test` cmd which would be useful to have in `pytest-runner`, reducing the need to use `--addopts`.

They are (https://github.com/pypa/setuptools/blob/master/setuptools/command/test.py):

>  ('test-module=', 'm', "Run 'test_suite' in specified module"),
>  ('test-suite=', 's', "Run single test, case or suite (e.g. 'module.test_suite')"),

While there are a few kinks in converting unittest 'suite' type args into pytest test names, even a very basic approach would be useful.

e.g. Allow `--test-suite=tests` instead of `--addopts="tests/"`

**Comment by jaraco** [comment]
The reason I chose to only expose `addopts` was because that's essentially the interface you get through configuration files... and I didn't want to add another way to do the same thing.

More importantly, `test-suite` as used by `setup.py test` doesn't have the same meaning. `test-suite` is a unittest TestSuite. `test-module` is a Python module.  `pytest` operates mainly on files and not modules/packages/suites.

I can't see how attempting to translate `--test-suite` to suitable args to `pytest` isn't going to just add confusion over passing any arguments directly to `pytest`.

If you can show a compelling use case, I might entertain a pull request, but in the example you give, while I see the `--test-suite=tests` to be slighly more appealing, doesn't seem worth the added hassle.

**Comment by jayvdb** [comment]
> pytest operates mainly on files and not modules/packages/suites.

Not really.  `--pyargs` exists to provide the latter, and I would expect pytest-runner to simply enable that to achieve `--test-suite=tests`

The main reason to do this is that it makes `[alias]\ntest=pytest` much closer to being a non-breaking drop-in solution.
